debug: false
server:
  port: 8088
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
    static-path-pattern: /**
  datasource:
    username: film
    password: 123
    url: jdbc:oracle:thin:@localhost:1521:orcl
    driver-class-name: oracle.jdbc.OracleDriver
  redis:
    port: 6379
    url: localhost
    